# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 189253b1370453f20d68fa9df4c9e5494e4a6fba144f724e3cd23219d66d85d6300b92a595050ce8d29cda7ca05ec4a7c899080711344ec741ddc3ef6556a3b7
test:
  secret_key_base: f4516715279c2d594ab741af73841389b2ab76cabe86869b1a1812a16bc19c3d166def93cb14a9d33d8fcf54f9debc80f145cd071fe27aa8e28c287643657637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
